# AI Project Cycle
![AI%20Project%20Cycle.png](attachment:AI%20Project%20Cycle.png)

# Average monthly temperature in Los Angeles: 2021

## 1. Problem Scoping (AI Project Cycle - Step 1)
In this notebook, we are going to apply the theory of descriptive statistics to discover information about a dataset.

We are trying to build an AI model to assist with weather prediction in Los Angeles. But before we start collecting data that we will train our AI model on, let’s just start by get a better understanding of the weather in Los Angeles.

## 2. Data Acquisition (AI Project Cycle - Step 2)
Dataset Source: https://weatherspark.com/y/1705/Average-Weather-in-Los-Angeles-California-United-States-Year-Round

This dataset is about the climate and average weather in Los Angeles, California, United States. We are going to deal with the average temperature of every month.

**Importing the required libraries**

In [1]:
import numpy as np
from scipy import stats

### 2.1. Creating a numpy array with the monthly mean temperatures in LA.
We will manually copy the recorded temperature highs and lows from the above link and save it into a numpy array in the below step.

<b>Note:</b> All temperatures are in Celsius.

In [2]:
highs = np.array([68, 68, 70, 72, 74, 78, 83, 84, 83, 78, 72, 67])
lows = np.array([49, 50, 52, 55, 59, 62, 65, 66, 64, 60, 53, 49])

In [3]:
print(highs)
print(lows)

[68 68 70 72 74 78 83 84 83 78 72 67]
[49 50 52 55 59 62 65 66 64 60 53 49]


## 3. Data Exploration (AI Project Cycle - Step 3)

### 3.1.1. Manually calculate the mean temperature
Manually calculate the mean high temperature of the entire year using the equation.

${mean} = \sum Monthly Temperature \div Number Of Months$

In [12]:
#student answer
sum = 0
for num in highs:
  sum += num

mean = sum / len(highs)
print(mean)

74.75


### 3.1.2. Calculate the mean temperature
Calculate the mean high temperature of the entire year using the numpy built-in function [mean()](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [90]:
#student answer

npmean = np.mean(highs)
print(npmean)


74.75


### 3.2.1. Manually identify the median temperature
Manually identify the median high temperature of entire year.

In [17]:
#The median is difficult to identify with the list out of order.
#We can use np.sort(x) to sort our list for us from lowest to highest.
np.sort(highs)

array([67, 68, 68, 70, 72, 72, 74, 78, 78, 83, 83, 84])

In [33]:
#Now identify the median from this list
#Student answer
nums = np.sort(highs)
mid = len(nums) // 2
median =  (nums[mid] + nums[~mid]) / 2
print(median)




73.0


### 3.2.2. Calculate the median temperature
Calculate the median temperature of entire year using the numpy built-in function [median()](https://numpy.org/doc/stable/reference/generated/numpy.median.html)

In [22]:
#student answer
npmedian = np.median(highs)
print(npmedian)


73.0


### 3.3.1. Manually identify the mode of the temperature values!
With the now sorted list, manually identify the mode of the high temperature values of the entire year.

In [89]:
from inspect import modulesbyfile
#student answer (submit your answer as a comment in this cell)
nums = np.sort(highs)
counts = dict()
for i in nums:
    counts[i] = counts.get(i, 0) + 1
mode = max(counts, key=counts.get)
print(mode)


68


### 3.3.2. Calculate the mode of the temperature values
Calculate the mode of the high temperature values of the entire year using the scipy built-in function in stats()

In [62]:
#student answer
mode_highs = stats.mode(highs)
print(mode_highs)

ModeResult(mode=68, count=2)


In [74]:
#student answer
mode = stats.mode(highs)
print(mode)


ModeResult(mode=68, count=2)


## 4. Repeat for the lows
We have calculated the mean, meadian and mode for the highs, now let's do the same for the lows.

Using numpy and scipy, calculate the mean median and mode for the lows array.

In [84]:
#student anwser for mean

np.mean(lows)


57.0

In [81]:
#student answer for median
np.median(lows)


57.0

In [83]:
#student answer for mode
stats.mode(lows)


ModeResult(mode=49, count=2)

## 5. Conclusion
We have now begun the process of understanding the weather in Los Angeles and what the trends are within our data. We have achieved this knowledge by calculating the mean, meadian and mode.